dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "ZbaiMTeNC2Z9qAKdHMdOczxxAijh+NnLKTUd6KMmTF/zX8H2DGUmhJXpc0UvAz2jS9Qx6tCU1OLSvhyIfz1OWAgzJ0jHJ6NbZzszJI4spbJFYztxhjm0H7jVwjTvWP6whrKjcaPdbRMltrAQeNahz
WRRcrk9/KSgvY8VH2B9Rh3dkElJ+jeIZFfc/8w5NXOoHWb7YbBOIprR/JftB181pKggx50szJgEsgNQ79YR9o/GJhHWLkD7Z3v8u/tO2vdVbD+qLlvirbPX+UL0SnwGKdVm/E7sW1uAhkNYGAAU5/ZB+YxD9lExX
LkxnkbVtM30YITNpQH3QKBTtnr/uJbkdnUwDDj/Fetm3hEHPmULcHuEecsnTc8u34OLFTQvUmQX0y+b/0Mr69Ocjf9T15VrdO85wa8PNjPxPCRuvaxGAsdRJV4WDMVZwL49Qa8q0aQNn0xzzyLwVAE7CFc916Icc
cudJy0hkb7jeTZP1CeuOlLRTvxy1Xrg0Pqkp+f9qnfo0wkDY9DFhrblc2ACjeeZkWPuAVzWdm7uASlQHT5hmDXvfLj3uK4SC/9JLP6TdcvcOYOV1iKz5UWAH/gwZrCbnhI+jJOsxE0JrSf5hcdivS0b10RVJn1x3
xui7r+YIX7Zkq4l2pimmf9IkLceRz5WwAMyT7zrfXXtdtSqs/X+1ss="

install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk12
      script:
        - mvn test -B
  